version: '3.8'

services:
  posthog-mcp:
    image: node:20-alpine
    container_name: posthog-mcp-server
    working_dir: /app
    volumes:
      - ./posthog-official-server.js:/app/server.js
    command: ["node", "server.js"]
    environment:
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_PROJECT_ID=${POSTHOG_PROJECT_ID}
      - POSTHOG_BASE_URL=https://eu.posthog.com
      - PORT=8082
    ports:
      - "8082:8082"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - posthog-mcp
    restart: unless-stopped