services:
  posthog-mcp:
    image: node:20-alpine
    container_name: posthog-mcp
    working_dir: /app
    volumes:
      - ./posthog-official-server.js:/app/server.js
      - ./.env:/app/.env
    command: ["node", "server.js"]
    environment:
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_PROJECT_ID=${POSTHOG_PROJECT_ID}
      - POSTHOG_BASE_URL=https://eu.posthog.com
      - PORT=8082
    networks:
      - mcp-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-mcp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-final.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - posthog-mcp
    networks:
      - mcp-network
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge