name = "timelines-mcp-auth"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# These will be set via wrangler secret put command
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# JWT_SECRET